name: auto runer

on:
  schedule:
    - cron: "0 6,18 * * *"   # 06:00 et 18:00 UTC (Abidjan = UTC)
  workflow_dispatch:          # déclenchement manuel possible

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r src/requirements.txt

      # Recrée le fichier JSON du service account à partir d’un secret GitHub
      - name: Write service account key
        run: |
          echo '${{ secrets.GDRIVE_SA_JSON }}' > sa.json

      - name: Run scraper
        env:
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: sa.json
        run: python main.py
